### ISSUE TITLE
Ασήμαντες διορθώσεις για το README

### ISSUE THREAD

**Issue by kipoujr** [Tsiompanis/BasicNeuralNet#1]
Θέλει μικρό γράμμα το example:
For Example:

Δύο φορές γραμμένο το how:
How how large (N

Δύο φορές γραμμένο το outputs:
target outputs outputs you give (O

Δύο φορές γραμμένο το παρακάτω:
NOTE: THE INPUT-OUTPUT VALUES MUST BE BETWEEN 0 AND 1
NOTE: THE INPUT-OUTPUT VALUES MUST BE BETWEEN 0 AND 1

Λείπει μία τελεία στην τελευταία πρόταση:
PLEASE WRITE AN ISSUE

Τέλεια δουλειά, καλή συνέχεια!!!

**Comment by Tsiompanis** [comment]
Thanks. Τέλος!
